name: Test Code

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests urllib3 pypdf openai

    - name: Run tests
      run: |
        python main.py

    - name: Upload downloaded.pdf
      uses: actions/upload-artifact@v4
      with:
        name: analysis-pdf
        path: ./analysis.md
